name: 'Wait'
description: 'Wait'
inputs:
  step-name:  # id of input
    description: 'Step Name'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/wait.sh ${{ inputs.step-name }}
      shell: bash